name: "Sample React CI Pipeline / Workflows"

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: "Clone Repo"
        uses: actions/checkout@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: "Check Node version"
        run: node --version

      - name: "List directories"
        run: ls

      - name: "Install Dependencies"
        run: npm install

      - name: "Run lint"
        run: npm run lint

      - name: "Run build"
        run: npm run build

      - name: "Run Test"
        run: npm test